hundred_correct_spelled_words =[list(['father', 'dysfunctional', 'selfish', 'drags', 'kids', 'dysfunction', '#run']),
 list(['thanks', '#lyft', 'credit', "can't", 'use', 'cause', 'offer', 'wheelchair', 'vans', 'pdx', '#disapointed', '#getthanked']),
 list(['bihday', 'majesty']) ,
 list(['listening', 'sad', 'songs', 'monday', 'morning', 'otw', 'work', 'sad']),
 list(['#sikh', '#temple', 'vandalised', '#calgary', ',', '#wso', 'condemns', 'act']),
 list(['thank', 'follow'])],
[list(['father', 'dysfunctional', 'selfish', 'drags', 'dysfunction', 'kiss', 'run']),
 list(['thanks', 'credit', 'use', 'cause', 'offer', 'wheelchair', '#getthanked', 'left', 'canst', 'van', 'pox', 'disappointed']),
 list(['majesty', 'midday']),
 list(['love', 'u', 'take', 'u', 'time', 'ur01Â', '0000Â', '000Â', 'Â', 'model']),
 list(['factsguide', 'society', 'motivation']),
 list(['22', 'huge', 'fan', 'fare', 'big', 'talking', 'leave', 'chaos', 'pay', 'disputes', 'get', '#allshowandnogo']),
 list(['camping', 'tomorrow', 'dandy']),
 list(['next', 'school', 'year', 'year', 'think', 'school', '#actorslife', '#revolutionschool', 'exam', 'Of', 'canst', 'that', 'Of', 'texas', 'hate', 'imagine', 'girl']),
 list(['won', '!', '!', '!', 'love', 'land', '!', '!', '!', '#clevelandcavaliers', 'Â', 'fallen', 'scars', 'champions', 'cleveland']),
 list(['welcome', '!', '!', 'ism', 'grm']),
 list(['consumer', 'price', 'index', 'climbed', 'previous', '02', '05', 'may', 'ireland', 'mon', 'blow', 'silver', 'gold', 'fore']),
 list(['selfish', '#standwithorlando', '#pulseshooting', '#orlandoshooting', '#biggerproblems', '#heabreaking', '#', 'orlando', 'selfish', 'values', 'love']),
 list(['get', 'see', 'daddy', 'today', '!', '!', '#80days', '#gettingfed']),
 list(['calls', 'middle', 'school', "'", 'build', 'wall', "'", 'chant', "'", "'", 'can', 'michigan', 'trot']),
 list(['comment', '!', '#opkillingbay', '#seashepherd', '#helpcovedolphins', '#thecove', '#helpcovedolphins', 'australia']),
 list(['ouchjunior', 'angry', '0', '#yugyoem', '#omgÂ', 'got', 'junior']),
 list(['thankful', 'paper', 'thankful', 'positive']),
 list(['agree', '!', 'between']),
 list(['!', '0', 'smiles', 'around', 'via', 'user', '#cookies', 'make', 'Â', 'Â', 'friday', 'in', 'people']),
 list(['know', ',', 'essential', 'oils', 'made', 'chemicals']),
 list(['#euro2016', 'people', 'blaming', 'ha', 'conceded', 'goal', 'fat', 'gave', 'away', 'free', 'kick', 'knowing', 'hit', 'money', 'able']),
 list(['sad', 'little', '#badday', '#coneofshame', 'due', 'cats', 'passed', 'funny', 'laughs']),
 list(['product', 'day', 'happy', 'man', 'tool', 'time', 'open', 'amp', 'drink', 'up', '!', 'wine', 'who', 'weekend']),
 list(['says', 'prove', 'lump', 'lump']),
 list(['#tgif', '#gamedev', '#indiedev', '#indiegamedev', '!', 'off', 'squad']),
 list(['beautiful', 'sign', 'vendor', '80', '4500', '!', '!', '#upsideofflorida', '#shopalyssas', 'love']),
 list(['!', '!', '00', '#pressconference', '!', 'sunday', '#throwback', '008Â', 'smiles', 'media', 'natalya', 'turkey', 'love']),
 list(['great', 'panel', 'mediatization', 'public', 'service', '#ica16']),
 list(['happy', 'day', '0000Â', 'Â', 'fathers']),
 list(['50', 'people', 'went', 'nightclub', 'good', 'night', '1', 'actions', 'means', 'people', 'lost', 'families', 'forever', 'manes', 'grip', 'orlando']),
 list(['never', 'chance', 'vote', 'presidential', 'candidate', 'excited', 'cycle', 'looks', 'different']),
 list(['#alohafriday', '#positivevibes', 'time', 'not', 'exist', 'hawaiian']),
 list(['rip', 'fellow', 'ireland', 'fan', 'passed', 'away', 'tonight', '!', ',', 'forever', 'singing', 'cheering', 'fire', 'northern', 'sadly', 'away']),
 list(['hard', 'monday', 'due', 'cloudy', 'weather', 'disabling', 'oxygen', 'production', 'today', '#goodnight', '#badmonday']),
 list(['unbelievable', 'century', 'need', 'something', 'like', '#neverump', '#xenophobia', 'must', 'weed']),
 list(['#taylorswift1989', 'bull', 'dominate', 'bull', 'direct', 'whatever', 'want', 'w']),
 list(['morning', '#travelingram', '#dalat', '#ripinkylife']),
 list(['one', 'word', 'tells', '#photoshop', '#enoughisenough', '#dontphotoshopeverything', '#wheresallthenaturalphotos']),
 list(['oh', ',', '#cedarpoint', 'waited', '2', 'hours', 'valravn', 'line', 'stopped', 'working', 'close']),
 list(['thankful', 'sunshine', 'thankful', 'positive']),
 list(['finally', 'finish', 'book', 'working', 'awhile', '#bookworm', '#ontothenextnovel']),
 list([',', 'fan', 'hard', ',', 'easier', 'fan', 'playoffs', 'roll', 'around', 'up', 'knocks', 'na', 'Of']),
 list(['life', 'social', 'networking', 'embrace', 'day']),
 list(['shares', 'snake', '!', 'see', 'weekend', '00', 'mon', 'midday', 'midday']),
 list(['lovely', 'echeveria', '#iphonesia', '#basilicabotanica', 'bloom', 'flowers', 'grow', 'gardening', 'bliss', 'bloom']),
 list(['amazing', 'diam', 'positive', 'affirmation']),
 list(['love', 'u', 'take', 'u', 'time', 'ur01Â', '0000Â', '000Â', 'Â', 'model']),
 list(['goes', 'whenever', 'in', 'something', 'wrong']),
 list(['feeling', 'blue', 'illustration']),
 list(['best', 'pa', 'life', 'knowing', 'are', '!', '0800Â', 'Â', 'Â']),
 list(['#abc2020', 'getting', 'ready', '2', 'remove', '#pulseclub', '#prayfororlando', 'victims', 'from']),
 list(['#bihday', 'got', '006000Â', 'Â', 'Â', 'Â', '#petunia', 'love', '0', 'nose', 'job', 'midday', 'you']),
 list(['concelebrate', '#albanpilgrimage', 'first', 'time']),
 list(['let', 'scumbaggery', 'begin']),
 list(['thank', 'you', '!', '00', 'super', 'love', '8', 'zpamdelacruz', '#', '@', 'it', 'wedding', 'doors']),
 list(['scourge', 'playing', 'pieces', 'piano', 'beyond', 'belief', 'barque']),
 list(['lets', 'fight', 'love', 'peace']),
 list(['happy', 'fathers', 'day']),
 list(['times', 'babe', '88', '#monochrome', '#instahappydayÂ', 'scot', 'scot', 'fashion', 'style']),
 list(['here', '!', '!', '00000', '#selfie', '#xoxo', '#like4likeÂ', 'weekend', 'solo']),
 list(['happy', 'work', 'conference', 'right', "'", 'leads', 'cultureofdevelopment', 'organizations', '#mindset', 'midst', 'work']),
 list(["grimmie's", 'last', 'performance', 'shot', 'via', '#christinarip', '#christinagrimmie', 'christian', 'voice']),
 list(['ready', 'dance', '#preschoolers', 'roar', 'students', 'proud']),
 list(['really', 'feelings', 'he']),
 list(['wife', 'adore', 'miss', 'poland', 'show', 'surgery', 'name', 'amp', 'everything', 'bridge']),
 list(['jealous', 'right', '#chatiado']),
 list(['celebrate', 'every', 'man', 'played', 'fatherly', 'role', 'day', '#', 'fathers']),
 list(['sure', 'happy', '000000Â', 'Â', 'Â', 'Â', 'ism', 'hours']),
 list(['white', 'establishment', 'running', 'around', 'loving', 'promoting', 'Â', 'the', 'canst', 'bulk', 'folk', 'greatness']),
 list(['good', 'morning', '!', 'journey', 'begins', '!', '00003Â', 'Â', 'Â', 'travel', '#thejourneybegins', 'yeah', 'hello']),
 list(['#', '#hottweets', 'like', 'venusexchangeÂ', 'blue', 'Of']),
 list(['new', 'arrived', '!', 'exciting', '!', '!', 'brochure', 'works', 'solutions']),
 list(['much', 'stuff', 'happening', 'florida', '!', 'first', 'shooting', '#disneygatorattack', 'two', 'year', 'old', 'kid', '00Â', 'Â', 'orlando']),
 list(['it00Â', 'sake', 'championship', 'clearly', 'turning', 'point', ',', ',', 'Â', 'ferri', 'up', 're', 'ferri', 'mercy', 'Of']),
 list(['first', 'test', '!', 'acid', 'proud']),
 list(['seeks', 'probe', '#udtapunjab', "'", 'leak', ',', 'points', 'finger', '#amarinder', ',', 'camp']),
 list(['wrapping', '#senseaboutmaths', 'th']),
 list(['hey', ',', 'white', 'people', 'call', 'people', "'", 'white', "'", 'race', 'identity', 'med']),
 list(['might', 'shown', 'today', 'regurgitated', 'talking', 'points', 'name', 'calling']),
 list(['sometimes', 'raise', 'brows', 'raise', 'bar', '#golfstrengthandconditioning', '#felixfoisgolf', 'strong']),
 list(['000', '#greathonour', '#careerconvos', 'user']),
 list(['designing', 'learning', 'space', 'include', '#wateringhole', '#mountaintop', 'h', 'innovative', 'cave', 'campfire']),
 list(['uses', 'amp', 'insecurity', 'lure', 'men', '#whitesupremacy', 'alright']),
 list(['carrying', 'gun', 'helped', 'take', 'gun', 'control', 'stop', 'black', 'market', '!', 'get', 'worse', '!', 'canst', 'terrorist']),
 list(['use', 'power', 'mind', 'body', '!', '!', '#altwaystoheal', '!', 'heal', 'healthy', 'peace']),
 list(['woohoo', '!', '!', '5', 'weeks', 'go', '!']),
 list(['far', 'away', 'place', 'family', 'members', 'his']),
 list(['ready', 'tonight', 'new', 'music', 'new', ',', 'look', 'announcement', '!', '#midweek', '#newmusic', '#watchthisspace', 'release', 'video', 'guitar']),
 list(['monday', 'nights', 'm', 'channel', '!', '!', '!', 'finally', 'get', 'see', 'fuss', 'about', '!', '!', '!', 'up', 'up']),
 list(['watching', 'new', 'episodes']),
 list(['nice', 'long', 'night', '0', '#snapchat', '#redhead', '#vermillionredÂ', 'office']),
 list(['15', 'things', 'incredibly', 'people']),
 list(['yes', '!', 'received', 'acceptance', 'letter', 'masters', 'back', 'october', '!', '#goodtimes', 'history']),
 list(['daughter', 'riding', 'bike', 'around', 'driveway', ',', 'son', 'playing', 'guitar', 'us', 'enjoy', 'campfire', '#summeime', 'Of', 'memories']),
 list(['!', '!', '!', 'loving', 'station', '!', '!', '!', 'way', 'jam', 'work', '!', '!', '!', 'getting', 'work', 'done', 'course', '!', '!', '!', 'org', 'memories']),
 list(['always', 'hope', 'one', 'day', 'get', 'hug', 'you', ',', 'think', 'happen', 'soon', 'ill', 'ill', 'donna', 'daytime']),
 list(['love', 'u', 'take', 'u', 'time', 'ur01Â', '0000Â', '000Â', 'Â', 'model']),
 list(['couple', 'sex', 'fat', 'naked', 'japanese', 'girls']),
 list(['day', '#humpers0Â', 'edwardsville', ',', 'hump', 'hump', 'Of', 'pennsylvania']),
 list(['personalised', '799', 'get', 'gap', 'shop', 'cool', 'home', 'fun'])]